# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/burstmaster',
                'doc_host': 'https://conorkeogh.github.io',
                'git_url': 'https://github.com/conorkeogh/burstmaster',
                'lib_path': 'burstmaster'},
  'syms': {'burstmaster.core': {'burstmaster.core.foo': ('core.html#foo', 'burstmaster/core.py')}}}
