# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/triggermate',
                'doc_host': 'https://conorkeogh.github.io',
                'git_url': 'https://github.com/conorkeogh/triggermate',
                'lib_path': 'triggermate'},
  'syms': {'triggermate.core': {'triggermate.core.foo': ('core.html#foo', 'triggermate/core.py')}}}
